name: ml_in_dart_01
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/Stef-GMS/ml_using_dart

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  ml_algo: ^16.15.1
  ml_dataframe: ^1.6.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
